---
apiVersion: v1
kind: Service
metadata:
  name: winnt-host
spec:
  type: NodePort
  selector:
    app: winnt
  ports:
    - protocol: TCP
      port: 3389
      targetPort: rdp
---
apiVersion: v1
kind: Service
metadata:
  name: winnt
spec:
  type: NodePort
  selector:
    app: winnt
  ports:
    - protocol: TCP
      port: 3389
      targetPort: ntrdp
    